# Autogenerated wrapper script for FP16_jll for any
export fp16_h

JLLWrappers.@generate_wrapper_header("FP16")
JLLWrappers.@declare_file_product(fp16_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        fp16_h,
        "include/fp16.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
